### ISSUE TITLE
Migrate from Gitlab

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#1]
- [x] Create the repo
- [x] Give access to CTO team
- [x] Add members
- [x] Move master and dev branches to Github
- [x] Protect master and dev
- [x] Set up labels and milestones (@mankoven)
- [x] Create a CSV that has all issues labeled "github" exported. Preserve author, title, date, description, label, milestone. No conversation required
- [x] Augment with cross-linkages to the original issue
- [x] Upload 1 row via API and test
- [x] Upload the rest and test
- [x] Archive the repo, preventing new commits and issues
- [x] Remove access to Gitlab for all except @sanand0 
- [x] Move all guide & doc references to code.gramener.com to github.com
- [x] Set up CI on Travis

**Comment by mankoven** [comment]
Created 28 labels and 8 milestones (till end of May 19)
