### ISSUE TITLE
Triggering notifications on completion of smart alerts

### ISSUE THREAD

**Issue by naveenreddymanukonda** [gramener/gramex#116]
We are using smart alerts to send mails once in a month in our project.
 - We need to notify some users by mail once we send all the smart alert emails.
 - Can we have a trigger parameter (should be called once smart alert is complete), which calls a function to send emails to other users with desired message from client.

**Comment by sanand0** [comment]
I'll be working on this over the next few days @naveenreddymanukonda

**Comment by naveenreddymanukonda** [comment]
Thanks @sanand0

**Comment by naveenreddymanukonda** [comment]
Thanks @sanand0 it is working as expected :)
