### ISSUE TITLE
Add showdown to UI components

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#118]
If enough projects need to use JS markdown conversion, we can add [Showdown](https://github.com/showdownjs/showdown) to the UI component library.

I prefer it over [Marked](https://github.com/markedjs/marked), though it's more popular. Showdown supports (out-of-box) some features that Marked does not:

- YAML metadata
- URL auto-linking
- Cross-link references

@pratapvardhan @bkamapantula Will this be useful?

**Comment by bkamapantula** [comment]
@sanand0 perhaps we could defer this to later please. don't see an immediate need
