### ISSUE TITLE
bootstrap-select version upgrade

### ISSUE THREAD

**Issue by PragnyaReddy** [gramener/gramex#138]
Current version of bootstrap-select in UI Components throws DOMException (https://github.com/snapappointments/bootstrap-select/issues/2221). Needs to be upgraded to v1.13.7 or above.

**Comment by pratapvardhan** [comment]
Opening due to regression in ab3c956 @sanand0

**Comment by sanand0** [comment]
Very sorry! Fixed via 49ebdac
