### ISSUE TITLE
FormHandler support aggregations without groupby

### ISSUE THREAD

**Issue by pratapvardhan** [gramener/gramex#145]
For example you might like to get `max` , `min`, `avg` of column `c1` using `flags?_c=c1|min&_c=c1|avg&_c=c1|max`  perhaps?  with `?<col><|><agg>` `|` being the separator.

```
results = df.agg({'c1': [min, max, 'mean']}).T

query = "SELECT MIN(c1), MAX(c1), AVG(c1) FROM "table_name"
```

```
  min   max       mean
 0.0  97.0  29.795918
```

Would be useful for quick explorations with formhandler.  Thoughts?

**Comment by sanand0** [comment]
Spec-wise, we can treat `?_by=` as a group-by on a constant, and it aggregates all other columns.

Could you share some real-life examples where you would use this, @pratapvardhan?

**Comment by pratapvardhan** [comment]
Quite didn't get the first part. Also want to get values from other columns, "SELECT MIN(c1), MAX(c2), AVG(c3) FROM "table_name"``

I'd use them for KPIs, summarized values for narratives. Let's discuss when we speak next.

**Comment by sanand0** [comment]
I meant that `flags?_by=_c=c1|min&_c=c1|avg&_c=c1|max` will do what you want.
