### ISSUE TITLE
Add documentation on responsive font sizes

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex#162]
# About
Bootstrap supports responsive font sizes via [rfs](https://github.com/twbs/rfs#class-boolean) utility.

# How to use
It can be enabled by `$enable-responsive-font-sizes: true` [scss variables](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L119).

Can we please document it and perhaps recommend it in the build validation too?

# Example
[Example](https://project-rfs.github.io/docs/4.3/examples/jumbotron/)   -- resize browser and notice font size changes in computed section in Inspect

![image](https://user-images.githubusercontent.com/1143687/57904230-7fb90880-788f-11e9-885d-2fc3f1a3223b.png)

**Comment by sanand0** [comment]
Added to the docs...

![image](https://user-images.githubusercontent.com/63734/57932991-af4b2d80-78ee-11e9-8a1d-73f2de50d11f.png)


... and to the theme picker

![image](https://user-images.githubusercontent.com/63734/57933001-b70ad200-78ee-11e9-8874-56fbda298525.png)
