### ISSUE TITLE
Specify the Loader parameter gramex.cache.open('yaml')

### ISSUE THREAD

**Issue by pratapvardhan** [gramener/gramex#164]
Use of PyYAML's `yaml.load` function without specifying the `Loader=...` parameter, has been deprecated. In PyYAML version 5.1, you will get a warning, but the function will still work. 

https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

Change

```
method = opener(yaml.load)
```

to 

```
method = opener(yaml.load, Loader=yaml.FullLoader)
```

@sanand0 thoughts?

**Comment by sanand0** [comment]
This is resolved by the use of [_yaml](https://github.com/gramener/gramex/blob/0083baaa061cb5a2daf2e71cf64b92420240288a/gramex/cache.py#L118-L121)
