### ISSUE TITLE
cache service for gramex.cache.query

### ISSUE THREAD

**Issue by pratapvardhan** [gramener/gramex#178]
`gramex.cache.query` stories it's cache in `gramex.cache._QUERY_CACHE`. Which is python dict with unfettered RAM storage. 

Should this rather be from a controlled cache service?

More specifically, for using it via `data.filter` and `formhandler`

**Comment by mniyas** [comment]
@pratapvardhan I tried loading 60 csv files (168MB each = 9.28GB) using gramex.cache. All of them got cached and was not getting replaced. As you mentioned, cache size should be controlled.

**Comment by mniyas** [comment]
@pratapvardhan [setup.py](https://github.com/gramener/gramex/blob/master/setup.py#L25) specifies cachetools >= 2.1. However, as we saw that the current memory size is not getting calculated properly using 2.1 version.

**Comment by pratapvardhan** [comment]
@mniyas -- Yes, I'll be updating that  to `cachetools >= 3.0` in upcoming release.

**Comment by pratapvardhan** [comment]
Fixed with #184
