### ISSUE TITLE
Remove guide installation and update install docs

### ISSUE THREAD

**Issue by pratapvardhan** [gramener/gramex#187]
"Please create a new PR that removes the guide installation. If people run Gramex without gramex.yaml, treat it as an empty gramex.yaml (or anything else that makes the code elegant = smaller)

Please change https://learn.gramener.com/guide/install/ to change "Gramex runs at http://127.0.0.1:9988/ and shows the Gramex Guide by default."
"

**Comment by sanand0** [comment]
Closed - no longer relevant
