### ISSUE TITLE
Improve documentation in DBAuth

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex#195]
in [DBAuth documentation](https://learn.gramener.com/guide/auth/#database-auth) please add the following note:

In the supporting file (database or flat file) do not create any column named, `user_id` since `gramex` uses this internally. Otherwise below error is thrown

```sh
update_user() got multiple values for argument `user_id`
```

![image](https://user-images.githubusercontent.com/1143687/64429191-132e7780-d0d3-11e9-8a44-e434abe55ab2.png)

**Comment by pratapvardhan** [comment]
In the dev, #192 we've changed user_id arg to _user_id, so yes, need to update docs not use column name `_user_id`

**Comment by mankoven** [comment]
@bharath4259 - Can you please include this in the PR for this cycle.

**Comment by bkamapantula** [comment]
closing as this is now available.
