### ISSUE TITLE
Support for distributed caching

### ISSUE THREAD

**Issue by mniyas** [gramener/gramex#198]
Gramex currently support in-memory caching and it is instance-based. 

- gramex.cache.query uses a dictionary
- gramex.cache.open uses TTLCache.
- formhandler is cached using gramex.cache.open

Can we enable Redis based caching for all of these so that the caching is distributed across instances?

**Comment by jaidevd** [comment]
Merged in 0e6f300154b344fe7c1dcfb574805c3a9027f570
