### ISSUE TITLE
Support for multiple connections in gramex query

### ISSUE THREAD

**Issue by mniyas** [gramener/gramex#199]
`gramex.cache.query` supports `state` parameter which is a query to the same DB table of the parent query. Can we provide a separate connection for the `state` query to utilise another metadata DB to validate cache?

**Comment by sanand0** [comment]
@mniyas Sorry about the delay on this. 

`gramex.cache.query()` already accepts `state=any_function`. You can define a function like this:

```python
def my_state():
    return gramex.cache.query(state_query, metadata_db_url)
```

Would that work for you?

**Comment by mniyas** [comment]
@sanand0 Yes, that works. Thanks
