### ISSUE TITLE
Request module not in dependency: No module named requests

### ISSUE THREAD

**Issue by samrudh** [gramener/gramex#201]
Summary
(On a fresh setup on Mac in new conda environment, python module **_requests_** installation is required while setting up UI components and built-in apps)

Steps to reproduce
After gramex installation run:
`gramex setup --all            `

Current bug behavior:
Below command failed with **ModuleNotFoundError: No module named 'requests'**
Gramex Version: 1.57.0
OS: Mac 10.14.5

Expected correct behavior:
setup installation of apps should start

Possible fixes
Add requests module as a dependency
For now: `conda install requests` or `pip install requests` should work

/label ~bug

**Comment by pratapvardhan** [comment]
fixed via 801a25f889b01fb3d5e3eaff087493ff518db61a
