### ISSUE TITLE
Cluster app issue

### ISSUE THREAD

**Issue by madhugramener** [gramener/gramex#205]
Hi - Gramex newbie here. I installed Gramex and cluster app, created a new dataset. The preview and select cluster tab is not being displayed. Any idea what is missing ? thanks for the help

![Cluster app issue](https://user-images.githubusercontent.com/58061164/69397888-eb33d500-0d0d-11ea-85f7-f7c8ab88493c.jpg)

**Comment by bkamapantula** [comment]
@madhugramener CSS looks off, do you see any errors in the gramex terminal please?

**Comment by somshubham** [comment]
@bkamapantula I have fixed, The issue is resolved now.
Thanks for pointing out bower install was not done.

**Comment by madhugramener** [comment]
Thank you Som, the bowerr install fixed it. Appreciate the help.
