### ISSUE TITLE
Dead links in the tutorial

### ISSUE THREAD

**Issue by Gunnvant** [gramener/gramex#208]
Hello, in the tutorial https://learn.gramener.com/guide/tutorials/dashboards/, 

- the step 1 that talks about "Working with formHandler", there is a dead link in where the reference to formHandler documentation is given. 
- Also it would greatly help if for the code snippet```<div class="formhandler" data-src="../data?_c=-Ship Date&_c=-Order Date&_c=-Order ID&_c=-Ship Mode&_c=-Quantity&_c=-Discount"></div>``` something can be written in place rather than referring to documentation. 

May be after mentioning that -colname will not show that column, a reference to the formHandler filters be made? Since, it took me awhile to locate the appropriate section in the formHandler docs.

**Comment by mankoven** [comment]
@Bharath R please pick this up.

**Comment by jaidevd** [comment]
@Bharath4259 please pick this up.

**Comment by bkamapantula** [comment]
thanks for raising this @Gunnvant! sorry for the long silence. I'll be reviewing this.

Broken links in Step 1: /data (this is relative to /quickstart which fails) in two instances.

correct link: https://learn.gramener.com/guide/tutorials/data

## Broken links - Part 2 - Quickstart

### Link to UI Components
In [step 2](https://learn.gramener.com/guide/tutorials/quickstart/#step-2-laying-out-some-scaffolding), UI Components is linked to 
https://learn.gramener.com/guide/tutorials/uicomponents which should be https://learn.gramener.com/guide/uicomponents

### Link to FormHandler Filters

In [Step 4](https://learn.gramener.com/guide/tutorials/quickstart/#step-4-adding-a-chart), link to FormHandler Filters should be https://learn.gramener.com/guide/formhandler/#formhandler-filters

### Link to Documentation

In [Next Steps](https://learn.gramener.com/guide/tutorials/quickstart/#next-steps), should the link to Detailed Documentation be https://learn.gramener.com/guide/ ?

@jaidevd I'll send a fix for these shortly.

**Comment by jaidevd** [comment]
Hi Bhanu,

The guide is also available at https://gramener.com/gramex/guide

Could you please change the learn.gramener.com links to the above? You
could do it only for the files you touch for now, or for the whole guide.
Your call.

Thanks,

**Comment by bkamapantula** [comment]
@jaidevd all changes are made relative to the paths, so no hard-coded `learn.gramener.com` URLs.

The deployment can be extended to `gramener.com/gramex/guide` instance too by @sanand0.

**Comment by sanand0** [comment]
CLosed via https://github.com/gramener/gramex-guide/pull/24
