### ISSUE TITLE
FacebookAuth is not handling user deny condition

### ISSUE THREAD

**Issue by Bharath4259** [gramener/gramex#209]
When using `FacebookAuth` in gramex after redirecting into the facebook login page, If user clicks on `"Not now"` button, the site is not redirecting back to the previous page.

![image](https://user-images.githubusercontent.com/30948353/70323108-f29cc780-1851-11ea-8666-3ce32a92b5a5.png)

**Comment by bkamapantula** [comment]
related to #196

**Comment by mankoven** [comment]
Workaround for the redirect error was provided via custom configuration in AuthHandler. Redirect URL mentioned as string.  (project-specific).
