### ISSUE TITLE
Docs for caching has errors

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#212]
https://learn.gramener.com/guide/cache/ mentions the cache configuration as `Cache-Control: public, max-age=315360000`

This needs quotes. `Cache-Control: "public, max-age=315360000"`

Thanks @pratapvardhan for the input.

**Comment by pratapvardhan** [comment]
Fixed at https://github.com/gramexrecipes/gramex-guide/commit/1ba3bbdf9156835904ddff06a2891b10ec499d4e
