### ISSUE TITLE
FileHandler returns incorrect MIME type if extension has capital letters

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#213]
[FileHandler checks file extensions to get the MIME type](https://github.com/gramener/gramex/blob/v1.58.0/gramex/handlers/filehandler.py#L285). But this fails if the extension has capital letters. For example:

```python
>>> mimetypes.types_map.get('.jpg')
'image/jpeg'
>>> mimetypes.types_map.get('.JPG')
None
```

Impact: .JPG files are served as text.

Solution:

- [x] [Replace](https://github.com/gramener/gramex/blob/v1.58.0/gramex/handlers/filehandler.py#L285) `self.file.suffix` with `self.file.suffix.lower()`
- [x] Add test cases to check the MIME type in [test_filehandler.py](https://github.com/gramener/gramex/blob/v1.58.0/tests/test_filehandler.py#L113)

**Comment by pratapvardhan** [comment]
closed via a96d729
