### ISSUE TITLE
Auth issue while running different gramex instances in same domain

### ISSUE THREAD

**Issue by mniyas** [gramener/gramex#214]
If I run 2 gramex instances with same domain in session settings, the `sid` is getting replaced every time I switch between instances.

eg: `app1.server.com` and `app2.server.com` have the domain as `.server.com` in the session settings. But they are 2 different gramex instances. So if someone logs in to one application and then goes to the second one, the user will get logged out of the first app since `sid` cookie is getting replaced by the second app in the browser.

**Comment by Bharath4259** [comment]
@mniyas  Please run both domains on two different gramex ports.

Lets say..
- `app1.server.com` > 9898,
- `app2.server.com` > 9988

**Comment by mniyas** [comment]
Fixed by this [commit](https://github.com/gramener/gramex/commit/87580396b961a3f1359772e0d578ee8063e3fd62)
