### ISSUE TITLE
Certificates error using CaptureHandler inside a container

### ISSUE THREAD

**Issue by mniyas** [gramener/gramex#225]
puppeteer is raising a `ERR_CERT_AUTHORITY_INVALID` error while opening https sites. This happens only in puppeteer running inside containers. 

Related bug: [Certificates error using  puppeteer](https://github.com/puppeteer/puppeteer/issues/2377)

**Comment by sanand0** [comment]
Closed via 595897a #226 

Thanks @mniyas
