### ISSUE TITLE
Didn't getting the  csv data output on screen using formhandler 

### ISSUE THREAD

**Issue by priyanshukumarcs049** [gramener/gramex#244]
when I follow up on the quickstart project in gramex tutorial and want to retrieve the CSV data. But it returns the cache flushing in session.json file in cmd.

after running  the server On Cmd I got the following msg: 

1. INFO    09-Jun 12:46:13 __init__ 9988 304 GET / (127.0.0.1) 2.03ms default
2. INFO    09-Jun 12:46:13 __init__ 9988 304 GET /ui/bootstraptheme.css (127.0.0.1) 2.00ms 
   apps/ui/bootstrap4-KT5ir
3. INFO    09-Jun 12:46:14 __init__ 9988 200 GET /favicon.ico (127.0.0.1) 1.99ms favicon
4. DEBUG   09-Jun 12:46:14 cache 9988 Flushing C:\Users\kpriy\AppData\Local\Gramex 
    Data\session.json.

I  also tried reinstalling gramex and all the other dependencies but still got the same error again and again.

**Comment by bkamapantula** [comment]
@priyanshukumarcs049 can you please share your gramex.yaml configuration?

**Comment by priyanshukumarcs049** [comment]
This is my gramex.yaml

import:
  ui:
    path: $GRAMEXAPPS/ui/gramex.yaml    # Import the UI components
    YAMLURL: $YAMLURL/ui/               # ... at this URL

url:
  superstore-data:
    pattern: /$YAMLURL/data
    handler: FormHandler
    kwargs:
      url: $YAMLPATH/store-sales.csv

**Comment by priyanshukumarcs049** [comment]
![Screenshot (50)](https://user-images.githubusercontent.com/31381774/84139207-1513d580-aa6d-11ea-9238-7046574c16bf.png)

@bkamapantula 
Please see this screenshot of cmd. This might help u on understanding my problem.
Thanks

**Comment by jaidevd** [comment]
@priyanshukumarcs049 
The session getting flushed is not the problem here. If you're not getting some data, means that some URL is not working. How are you trying to get the CSV?

**Comment by priyanshukumarcs049** [comment]
@jaidevd u can see the gramex.yaml file:
url:
  superstore-data:
    pattern: /$YAMLURL/data
    handler: FormHandler
    kwargs:
      url: $YAMLPATH/store-sales.csv

I kept the csv data in the same destination folder and follow the instruction mention here in quickstart tutorial https://learn.gramener.com/guide/tutorials/quickstart/#step-3-filling-in-the-data

**Comment by sanand0** [comment]
It looks like the file write is getting blocked. I've seen this happen when multiple Gramex instances are running, and one of them locks session.json.

I usually avoid this by having a separate session.json for each session (or a Redis session cache like @mniyas uses).

But it would be interesting to debug this. @priyanshukumarcs049 Could we get on a screen-sharing session on Fri morning, perhaps around 11 am IST? We can connect at https://meet.google.com/npb-ceai-vtp

**Comment by priyanshukumarcs049** [comment]
@sanand0 Thank you for responding. Looking forward to the discussion.

**Comment by sanand0** [comment]
Summary of the problem:

- This has nothing to do with session flushing. The session was flushed properly. There were no messages after that on the log, that's all
- However, the content encoding was getting mixed -- UTF-16 vs UTF-8. It's not clear if this is a system setting issue or a file setting issue (`index.html` was in UTF-16).

@priyanshukumarcs049 can we speak on Mon 15 Jun at 1 pm to debug at https://meet.google.com/nsm-apqd-izh?

**Comment by priyanshukumarcs049** [comment]
@sanand0 sure. Thanks

**Comment by sanand0** [comment]
This seems to be caused by a UTF-16 LE setting issue -- we don't know where that came from.

But deleting the files and re-creating them solved the problem. Thanks for raising @priyanshukumarcs049
