### ISSUE TITLE
Test refactoring notes

### ISSUE THREAD

**Issue by jaidevd** [gramener/gramex#245]
[Current test stats](https://travis-ci.com/github/gramener/gramex/builds/170230130) from the dev branch:
* nosetests takes ~ 4 minutes
* 12 errors
* 16 failures

[This branch](https://github.com/gramener/gramex/tree/jd-build-profile) has the following stats:
* Shaves off ~ 30 seconds from tests
* 5 errors
* 11 failures

Summary of changes:
* Fix deprecations warnings that have turned into errors
* Update rpy2 to be compatible with Pandas 1.x
* Twitter API keys might need regenerating
* Remove gramex EE tests

**Comment by sanand0** [comment]
@jaidevd Is this still relevant? Or should we drop this?

**Comment by sanand0** [comment]
A typical build currently takes ~9 minutes. 4.5 minutes out of this is the setup (creating the environment, conda install, pip install, gramex setup, etc.) 

If Travis has the option of caching pip & yarn, or running custom docker containers with Anaconda / dependencies pre-installed, we can cut down 4 minutes I think.
