### ISSUE TITLE
Running gramex

### ISSUE THREAD

**Issue by SaurabhKhemka** [gramener/gramex#249]
I am trying to set up a project using https://learn.gramener.com/guide/install/

But when I run the command gramex, it gives an error.

\appdata\local\programs\python\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError

Kindly help.

**Comment by jaidevd** [comment]
@SaurabhKhemka This is a [known issue](https://github.com/tornadoweb/tornado/issues/2751) with Tornado and Python 3.8.
You could use the fix suggested in the issue, or use Python 3.7 temporarily. Meanwhile, we'll release a new version of Gramex that fixes this for Python 3.8. Watch this space.

Thanks,

**Comment by SaurabhKhemka** [comment]
Which version of python 3.x should I use?

**Comment by jaidevd** [comment]
@SaurabhKhemka You can use Python 3.7 for now.
