### ISSUE TITLE
CaptureHandler crashes on long-running browser instance

### ISSUE THREAD

**Issue by mniyas** [gramener/gramex#256]
CaptureHandler crashes with the following error after running for long duration
`WebSocket is not open: readyState 3 (CLOSED)`

Related bug: https://github.com/puppeteer/puppeteer/issues/4428

Possible fix:
```
 chromecapture.js#132

  // if (typeof browser == 'undefined') 
  //     browser = await puppeteer.launch({args: args})
  browser = await puppeteer.launch({args: args})
  browser.on('disconnected', () => {
    render(q);
  });
```
The commented block is checking for `browser` type and is returning false in 2nd call. I've commented this. Didn't understand the need for this check though.

**Comment by sanand0** [comment]
This looks like it could work. You may need to set `browser = undefined` as well.

It would be good to write a test case so that when `?_test_disconnect=1`  is passed, it disconnects the browser and tests this branch, please.

**Comment by sanand0** [comment]
@mniyas I'd like to include this fix in this month's release. Would you be able to spare time to work on the test case? If not, we'll take it up.
