### ISSUE TITLE
Gramex installation steps - Conda method

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex#263]
Currently the Installation steps (at [Install](https://learn.gramener.com/guide/install/)) are as follows:

1. Install Anaconda (any version from 5.2.0 to 2019.10)
2. Install node.js 10 or later.
3. On a Mac, install Xcode.
4. Run the following commands on the terminal

```bash
pip install gramex      # Install latest version of Gramex
npm install -g yarn     # Required for UI components and built-in apps
gramex setup --all      # Set up UI components and built-in apps
```

5. Create an empty `gramex.yaml` text file in a directory
6. Run `gramex` from that directory

Gramex runs at `http://127.0.0.1:9988/` and lists the files in your folder by default. Press Ctrl-C to exit Gramex.

# Proposed change
Create a new installation method with steps as is but in a conda environment as it's easier to manage dependencies.

thoughts @sanand0, @jaidevd?

**Comment by sanand0** [comment]
Subset of #254
