### ISSUE TITLE
Auth for all handlers

### ISSUE THREAD

**Issue by mniyas** [gramener/gramex#277]
app:
      listen:
        port: 8000
      settings:
        auth: True

As per the [documentation](https://learn.gramener.com/guide/auth/#authorization) this snippet should enable auth for all handlers. But this is not working.

**Comment by sanand0** [comment]
Thanks for raising this @mniyas. It's resolved.

There's also a documentation bug. It should have been

```yaml
app:
  listen:
    port: 8000
  auth: true
```

I have corrected the [Gramex Guide](https://learn.gramener.com/guide/auth/#authorization) accordingly.
