### ISSUE TITLE
 data is missing in log files, causing issues with logviewer

### ISSUE THREAD

**Issue by naveenreddymanukonda** [gramener/gramex#279]
When we try to create new logviewer.db by deleting or moving the existing logviewer.db some data is missing in the DB for the old days the same is reflecting in request.csv also.

- Data in gramex.log.date and requests.csv.date was lost compare to few weeks ago, when it was present in gramex.log and requests.csv

**Comment by pratapvardhan** [comment]
To clarify: logviewer doesn't modify log files. The issue here is archived log files both (requests.csv and gramex.log) don't have the data that were seen few days ago. Possibilities include archiving job failed or file content was manually deleted.

**Comment by pratapvardhan** [comment]
Observation from server: two applications were writing logs to same location. One possibility -- log file was locked by one instance and probably flushed by same / another. cc @jaidevd @sanand0

**Comment by sanand0** [comment]
Proposed actions: Add documentation explaining...

- [ ] how to manage logs when running multiple instances of the same app
- [ ] how to configure logviewer for multiple instances of the same app

**Comment by sanand0** [comment]
Closed via gramener/gramex-guide@fce5799
