### ISSUE TITLE
Client-side CaptureHandler

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#285]
Raised by @naveenreddymanukonda

CaptureHandler requires the page to be re-rendered. If the page load is 5 seconds, CaptureHandler takes an additional 5 seconds.

Can we capture the rendered contents of

- [ ] a single chart (HTML + SVG) as an image
- [ ] a full page as an image

### Client-side re-rendering

These libraries re-create the computed DOM (with embedded images, web-fonts) into an SVG `<foreignObject>` and render it as an `<img>` that can be saved as PNG.

1. **[html2canvas](https://github.com/niklasvh/html2canvas) (2020, 21.5K★)** seems most mature. [Tests](https://html2canvas.hertzen.com/tests/) work with most HTML + SVG elements
2. [html-to-image](https://github.com/bubkoo/html-to-image) (2020, 382★) forks from [dom-to-image](https://github.com/tsayen/dom-to-image) (2017, 6.5K★) forks from [domvas](https://github.com/pbakaus/domvas) (2013). 
3. [saveSvgAsPng](https://github.com/exupero/saveSvgAsPng) (2020, 1K★) has a similar approach.

### Plugin-based

1. [Element screenshot](https://chrome.google.com/webstore/detail/element-screenshot/mhbapdljigafafoimcnnhagdclejnkcf) take a screenshot of a DOM element.

**Comment by sanand0** [comment]
@naveenreddymanukonda I will evaluate libraries for this by this weekend and revert by Monday 14 Sep 2020 noon with options.

**Comment by naveenreddymanukonda** [comment]
Thanks, @sanand0

**Comment by sanand0** [comment]
@naveenreddymanukonda [html2canvas](https://github.com/niklasvh/html2canvas) seems most mature. See [this question](https://stackoverflow.com/a/50300880/100904) on how to download. Could you please let me know if it works? If yes, we'll incorporate it

**Comment by sanand0** [comment]
@naveenreddymanukonda did html2canvas work?

**Comment by naveenreddymanukonda** [comment]
@sanand0 we are facing a few issues while implementing the html2canvas in few pages we are checking on that

**Comment by sanand0** [comment]
The following errors were reported by html2canvas.

![image](https://user-images.githubusercontent.com/63734/93863478-29f53b80-fce1-11ea-9d28-67e8d3940e31.png)
![image](https://user-images.githubusercontent.com/63734/93863499-2feb1c80-fce1-11ea-8f4e-289d83e4b6ff.png)

These were caused by dropdowns inside the selector -- with the width and height being reported as zero. Hiding them solves the issue.

```js
$('.right-dropdown').addClass('d-none')
html2canvas(document.querySelector(selector), {})
.then(canvas => {
  canvas.toBlob(blob => {
    saveAs(blob, d_name +'_'+ i_name.replace("₹", "Rupee") + ".png"); // FileSaver.js function
  });
})
$('.right-dropdown').removeClass('d-none')
```

This needs to be documented
