### ISSUE TITLE
Offline install

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#287]
Allow users to install Gramex on a system without an Internet connection, and document this on the Guide.

- [x] Install offline on Docker @bhatsandeep 
- [x] Install offline on Linux @jaidevd 
- [x] Install offline on Windows @sanand0

**Comment by sanand0** [comment]
Create the offline package:

- Download Anaconda
- Create a [pypi mirror](https://pypi.org/project/python-pypi-mirror/) with all packages from gramex/release.json


Install from offline package:

- Install Anaconda
- Run `python3 -m http.server` on the pypi mirror folder, and run `pip install -i http://127.0.0.1:8000/simple -r package-list`

**Comment by sanand0** [comment]
Alternate approach:

On a system **with an Internet connection** and the **same platform** (Windows/Linux) as the target system:

1. Install Gramex using `conda` into a folder called `offline`
2. Copy the `offline` folder into the target system

@bhatsandeep -- I prefer this approach because I can't see any other way of installing puppeteer. Is this fine?
@jaidevd -- could you try this on Linux?
I'll verify on Windows.

**Comment by sanand0** [comment]
@jaidevd any luck trying this on Linux?

**Comment by jaidevd** [comment]
@sanand0 Here: https://github.com/gramener/gramex/pull/295

**Comment by sanand0** [comment]
Closing this via documentation at gramener/gramex-guide@d44e692 gramener/gramex-guide@ee39773

Pull #295 will be independently merged after testing.
