### ISSUE TITLE
No tag for latest release

### ISSUE THREAD

**Issue by jaidevd** [gramener/gramex#293]
The [latest release](https://pypi.org/project/gramex/) on PyPI is v1.63.1, but no such git tag exists.

This is a problem because the conda recipe picks up the version from `release.json`, and needs to check out the tag before building the conda package.

**Comment by sanand0** [comment]
Got it. I had pushed it to PyPi to test an offline build method. I guess I'll have to release 1.63.1 formally, then. I'll do this by tomorrow (22 Sep 2020 1 pm IST).

**Comment by sanand0** [comment]
Fixed via 040b82a4 into tag 1.63.2. But please note that this is an untested version and should not be placed on DockerHub.
