### ISSUE TITLE
Replace moment.js in UI Components

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex#294]
[UI Components](https://learn.gramener.com/guide/uicomponents/) ships with `moment.js`.

Moment.js project is now considered _done_ and only critical security issues and bugs will be addressed. Read at https://momentjs.com/docs/#/-project-status/

"We now generally consider Moment to be a legacy project in maintenance mode. It is not dead, but it is indeed done."

Todo: find alternative for moment.js and include in UI Components.

**Comment by sanand0** [comment]
Of the alternatives proposed, [dayjs](https://github.com/iamkun/dayjs/) seems the smallest and most popular. If no alternatives are proposed by 28 Sep 2020, I'll go with this.

Whichever alternative we pick, we need to:

- Add it to the UI Component library
- Replace moment.js in gramex init
- Document the change on the Guide

Suggestions on alternate libraries welcome.
