### ISSUE TITLE
GoogleAuth is broken on the master branch

### ISSUE THREAD

**Issue by jaidevd** [gramener/gramex#298]
As of 1698689b0fae9ce11d30a2b47ca01d33d35cbf94, GoogleAuth does not work. Nothing changed in my gramex config or the Google developer console. The endpoint shows the following error:

```
Error 400: invalid_request
Invalid parameter value for redirect_uri: Missing scheme: /google?next=%2F
```

This works fine on the release branch. @sanand0 I suspect something went wrong [here](f8edaeebf08c3c7bca31b10e6a7c3d755d2b9312).

**Comment by sanand0** [comment]
@jaidevd I broke it while trying to implement X-Request-URI. Basically, I'm forcing all redirects to be relative URLs (for no reason). Will fix by this weekend.

**Comment by jaidevd** [comment]
@sanand0 Sorry, made a mistake in reporting this. It doesn't work on the release branch either. It just so happened that my release branch was old.

**Comment by sanand0** [comment]
This was introduced in f8edaeeb and is part of the 1.63.2 internal release. I'm fixing this now.
