### ISSUE TITLE
Extendability - ModelHandler

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex#303]
- accept import paths (scikit, tensorflow, keras) in YAML similar to path arg currently for files
- complete an end-to-end ML task with ModelHandler: add, train, test, predict, download
- add a demo for this
- include a DL model

**Comment by jaidevd** [comment]
Thanks, @bkamapantula 
As a next step, @sanand0 , could we find a way to let Gramex users register their own callbacks for `gramex.cache.open`?

**Comment by sanand0** [comment]
Agreed. Adding to the 1 Nov release.

**Comment by sanand0** [comment]
@jaidevd The master branch lets you register custom callbacks. For example:

```python
        gramex.cache.open_callback['shp'] = geopandas.read_file     # Register
        prs = gramex.cache.open('my.shp', layer='countries')        # Open with method
```

[See docs](https://learn.gramener.com/gramex/gramex.html#gramex.cache.open)

Now, what do we do to accept TensorFlow or Keras models?

**Comment by jaidevd** [comment]
Keras models are loaded as follows:
```python
>>> from tensorflow.keras.models import load_model
>>> model = load_model('mymodel.h5', **kwargs)
```
`*.h5` is already a callback. So I'd suggest that we find a way to invoke the Keras callback _only_ when it's within a `ModelHandler` scope. After that, we just have to make sure that Keras models are invoked via Tensorflow's [`scikit-learn` wrappers](https://www.tensorflow.org/api_docs/python/tf/keras/wrappers/scikit_learn)

That should do it.

**Comment by jaidevd** [comment]
BTW, in a recent release, scikit-learn estimators and pipelines come with an [HTML representation](https://scikit-learn.org/stable/auto_examples/compose/plot_column_transformer_mixed_types.html#html-representation-of-pipeline).

It would be really cool if we had a feature such that when a ModelHandler is specified in gramex.yaml, it includes by default an endpoint which shows the HTML diagrams of all models under it.

Suppose:
```yaml
url:
  modelhandler:
    pattern: /$YAMLURL/model/(.*?)/(.*?)
    handler: ModelHandler
    kwargs:
      path: $YAMLPATH  # The local directory to store model files/training data etc.
```

Then, something like `/$YAMLURL/model/_prettify` shows the diagrams.

**Comment by pratapvardhan** [comment]
Should we rather explicitly use `gramex.cache.open('data.h5', load_keras_model, arg='value')` inside ` gramex.ml` / `modelhandler.py`. We perhaps want to optionally load (keras, TensorFlow, etc) and explicitly mention `engine=keras,pytorch`?

**Comment by sanand0** [comment]
Agree on both something like `/model/_prettify` and `engine=keras|pytorch`.

**Comment by sanand0** [comment]
This feature has slipped by a month and will be planned for the December release
