### ISSUE TITLE
NameError: name 'python_file' is not defined | slidesense

### ISSUE THREAD

**Issue by kamleshdjango** [gramener/gramex#306]
**Is something not working as expected?**
Trying to import python function from a python file
`run slidesense` 
NameError: name 'python_file' is not defined

**Steps to reproduce.**
Please help us reproduce the bug, by sharing:
1. `rules:
        - copy-slide: df
          data:
            custom1:
              function: python_file.func(copy.val["serial_no"])
`
2. Screenshot attached
![image](https://user-images.githubusercontent.com/17406181/95447891-19e78800-0980-11eb-8b6f-79dea8995ddc.png)

**Comment by jaidevd** [comment]
Thanks for pointing this out, @kamleshdjango 
Could you also share the Gramex version which caused this error?
@sanand0 could you please take a look?

**Comment by kamleshdjango** [comment]
Gramex version 1.62
I have tested on Gramex 1.64 as well. Please give it a try.

**Comment by sanand0** [comment]
I'll have a fix for this in the next release. Thanks @kamleshdjango !
