### ISSUE TITLE
Extend JSONHandler to work with YAML

### ISSUE THREAD

**Issue by jaidevd** [gramener/gramex#308]
**Is your feature request related to a problem? Please describe.**
We'd like `JSONHandler` to work with YAML files as well.

**Describe the solution you'd like**
Extend JSONHandler, (as done in the IDE), and push the changes back to JSONHandler

ToDos:
- [ ] Add a `prepare` kwarg to JSONHandler
- [ ] Most of `JSONHandler.jsonwalk` can be done with `gramex.cache.open`
- [ ] Add a `parse` kwarg to JSONHandler (potentially to replace `JSONHandler.parse_body_as_json`)

**Comment by sanand0** [comment]
Closing as deferred
