### ISSUE TITLE
JSONHandler: Option to provide default key

### ISSUE THREAD

**Issue by pratapvardhan** [gramener/gramex#314]
**Is your feature request related to a problem? Please describe.**
https://learn.gramener.com/guide/jsonhandler/#get-read-data -- currently if you don't provide any key. Entire json is returned. It would be useful to have an option to provide default key?

**Describe the solution you'd like**
In case a valid default key is provided, return data.get(default_key) instead of data.

**Comment by sanand0** [comment]
I think re-using a structure like [FormHandler defaults](https://learn.gramener.com/guide/formhandler/#formhandler-defaults) would help.

In fact, this could be useful for **all handlers**. We could add this to `BaseHandler.prepare()`

What do you think, @pratapvardhan?

**Comment by pratapvardhan** [comment]
Agree, defaults for all handlers, will make it useful and consistent.

**Comment by sanand0** [comment]
Closing as deferred
