### ISSUE TITLE
TypeError when subclassing handlers

### ISSUE THREAD

**Issue by jaidevd** [gramener/gramex#316]
**Is something not working as expected?**
If a subclassed handler contains a method which has a `super` call, it raises a `TypeError: self is not an instance of SomeHandler`

**Steps to reproduce.**
Say I have a class `ide.ConfigHandler`, which is a subclass of `gramex.handlers.JSONHandler`, containing a `prepare` method that is like:
```python
class ConfigHandler(JSONHandler):
    def prepare(self, *args, **kwargs):
        # some logic
        super(ConfigHandler, self).prepare(*args, **kwargs)
```
then the last line fails intermittently, mostly when the config gets reloaded. It turns out that `self` unexpectedly becomes an instance of `gramex.services.ide.ConfigHandler` instead of just `ide.ConfigHandler`.

**Expected behavior**
`self` should be an instance of `ide.ConfigHandler` instead of `gramex.services.ide.ConfigHandler`

**Your environment:**
 - Gramex version: latest release branch

**Additional context**
This seems to happen whenever the config reloads.

**Comment by sanand0** [comment]
@jaidevd could you share a full trace, please?

**Comment by jaidevd** [comment]
@sanand0 Here it is:
```
ERROR   16-Oct 06:08:25 web Uncaught exception GET /cfg/vamsi/
HTTPServerRequest(protocol='https', host='gramex.gramener.com', method='GET', uri='/cfg/vamsi/', version='HTTP/1.0')
Traceback (most recent call last):
  File "/mnt/data/apps/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1569, in _execute
    result = self.prepare()
  File "/home/ubuntu/ide/ide.py", line 101, in prepare
    super(ConfigHandler, self).prepare(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
ERROR   16-Oct 06:08:25 __init__ 9988 500 GET /cfg/vamsi/  3.20ms ide-config-handler
```

**Comment by jaidevd** [comment]
A workaround is to use
```python
JSONhandler.prepare(self, *args, **kwargs)
```
instead of
```python
super(ConfigHandler, self).prepare(*args, **kwargs)
```

**Comment by sanand0** [comment]
@jaidevd I created a gramex.yaml

```yaml
url:
  home:
    pattern: /(.*)
    handler: subclass.ConfigHandler
    kwargs:
      path: $YAMLPATH/data.json
```

... and a `subclass.py`

```python
from gramex.handlers import JSONHandler

class ConfigHandler(JSONHandler):
    def prepare(self, *args, **kwargs):
        print('Preparing...')
        super(ConfigHandler, self).prepare(*args, **kwargs)
```

... and tried rerunning it about 100 times. It hasn't failed so far. Is there some other circumstance that makes this fail?

**Comment by jaidevd** [comment]
@sanand0 While gramex is running, try making some spurious changes to `gramex.yaml`, save them, and see?

**Comment by sanand0** [comment]
This is deferred until we can reliably reproduce it.

**Comment by sanand0** [comment]
Closing for now, marking with the deferred label
