### ISSUE TITLE
Forms builder - Save form screenshot to database

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex#325]
**Is your feature request related to a problem? Please describe.**
This is related to and is a sub-feature of #324

**Describe the solution you'd like**
During form publishing, a screenshot of the form should be taken and saved to the database.

Screenshots for each form are retrieved again to render the gallery page.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by sanand0** [comment]
This will be delivered as part of the Dec release
