### ISSUE TITLE
Forms builder - Embed a form

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex#326]
**Is your feature request related to a problem? Please describe.**
This is related to and a sub-feature of #324 

**Describe the solution you'd like**
Once a form is published, users should be able to embed it as below (or similar):

```js
<script type="text/javascript" src="ui/forms/dist/forms.min.js"></script>
<script>
 $('.form-container').forms({id: 'FORM_ID'})
</script>
```

It should fetch the related styles, HTML and embed in the target page.

Embed the form option should be available in `/forms/form/ID` page along with the view source option.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by sanand0** [comment]
This will be delivered as part of the Dec release

**Comment by sanand0** [comment]
Proposed embed API:

```html
<div id="gramexform-9349"></div>
<script src="https://gramener.com/gramexforms/embedscript.js"></script>
```

The first line can be placed where the user wants to embed form 9349. The second line is a script that inserts all forms. A crude implementation could look like this:

```js
$('[id^="gramexform-"]').each(function () {
  var $this = $(this)
  $.getJSON('https://gramener.com/forms/json/' + $this.attr('id').replace(/^gramexform-/, ''))
    .done(function (config) {
      $this.formbuilder(config)
    })
})
```
