### ISSUE TITLE
Allow all handlers to support methods

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#329]
Support `methods: [POST]` in DBAuth, SimpleAuth and other auth handlers.

Raised by @bkamapantula for Abhilash

**Comment by sanand0** [comment]
This will be delivered as part of the Dec release

**Comment by println2** [comment]
@sanand0 can I contribute this one ?

**Comment by sanand0** [comment]
@println2 DEFINITELY! Thank you 😉

**Comment by sanand0** [comment]
@println2 -- you can:

- In BaseMixin.setup, add a `methods=None` kwarg and a line `cls.setup_http_methods(methods)`.
- Create a classmethod `BaseMixin.setup_httpmethods(cls, methods)`. This should do 2 things:
  - If methods is None, do nothing and return. Else:
  - Convert the methods, which can be a list or a comma or space separated string in any case into a SET in lowercase and store this in `cls._http_methods`
    - `method='GET post,  Put'` -> `{'get', 'post', 'put'}`
    - `method=['GET ', ' Post ', 'put,']` -> `{'get', 'post', 'put'}`
    - One way is to join any array into a string, convert to lowercase, and split using comma or space, convert to a set
  - Add a `cls._on_init_methods.append(cls.check_http_method)`
- Create `BaseHandler.check_http_method(self)`. This will raise a `http.METHOD_NOT_ALLOWED` if `self.request.method` is not in `self._http_methods`

**Comment by sanand0** [comment]
- Set up Gramex locally to be able to run the tests using `make test-setup`
- In `tests/gramex.yaml`, add a ProcessHandler `process/get-only:` key with a `methods: GET`
- In `tests/test_process_handler`, add a `TestProcessHandler.test_methods()` method. This should check that:
    - GET works `self.check('process/get-only')`
    - POST fails: `self.check('process/get-only', method='POST', code=METHOD_NOT_ALLOWED)`
- Similarly for FormHandler with `methods: "GET,PUT DELETE, OPTIONS"`. This should check that GET, PUT and DELETE work, but POST does not.
- Add another FormHandler with `methods: [GET, PUT, DELETE]` and check the same.
