### ISSUE TITLE
Improve CLI help

### ISSUE THREAD

**Issue by jaidevd** [gramener/gramex#347]
**Is your feature request related to a problem? Please describe.**
`gramex --help` or `gramex <subcommand> --help` could be made better

**Describe the solution you'd like**
For all the subcommands available under the `gramex` command, 
- [ ] gramex init
- [ ] gramex service
- [ ] gramex mail
- [ ] gramex license
- [ ] gramex install
- [ ] gramex update
- [ ] gramex setup
- [ ] gramex run
- [ ] gramex uninstall

there should be more verbose help messages. Currently, running `gramex --help` and `gramex <subcommand> --help` shows me the same message.

Instead, the latter should show me help specific to the subcommands. 
For instance, I'd like to know what cmd options are available for each subcommand.

**Comment by sanand0** [comment]
Will add it for the next release.
