### ISSUE TITLE
Windows - gramex setup --all fails - Microsoft JScript compilation error 

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex#353]
**Is something not working as expected?**
Gramex app setup fails causing `style.scss` compilation to fail in applications.

**Steps to reproduce.**
Please help us reproduce the bug, by sharing:
1. install node.js 10.x
2. create a conda environment
3. install gramex: `pip install gramex`
4. setup apps: `gramex setup --all`

![image](https://user-images.githubusercontent.com/1143687/102763502-a8f62080-4371-11eb-8202-bdba1e3bfee0.png)

**Expected behavior**
`gramex setup --all` should have run smoothly without errors.

I came across this in two different machines.

**1st environment:**
 - Windows 10
 - Python version: 3.6.3
 - Gramex version: 1.66

**2nd environment:**
 - Windows 10
 - Python version: 3.7.6
 - Gramex version: 1.66

**Comment by bkamapantula** [comment]
[master branch](https://github.com/gramener/gramex/blob/master/gramex/apps/ui/package.json) doesn't ship with postinstall.js setup while [1.66 does](https://github.com/gramener/gramex/blob/v1.66.0/gramex/apps/ui/package.json#L40).

possible fix: release 1.66.1 that's in sync with the master branch

**Comment by sanand0** [comment]
I'll fix this by Fri 25 Dec, and plan a release ASAP.

**Comment by jaidevd** [comment]
This will be fixed in Gramex v1.67. We will not be releasing a v1.66.1 - this means that v1.66 will be a known buggy release. @sanand0 Can you please mention this in the 1.66 release notes? We can close this then.

**Comment by sanand0** [comment]
Added in [Gramex Guide 1.67 release notes](https://github.com/gramener/gramex-guide/commit/e90544ae3f5c52ccc156ffd4a910e16a61cc720c)
