### ISSUE TITLE
Autoreload doesn't work in conda environment 

### ISSUE THREAD

**Issue by pratapvardhan** [gramener/gramex#363]
```bash
INFO    28-Jan 20:01:11 autoreload D:\projects\yolo\__init__.py modified; restarting server
D:\apps\Miniconda3\envs\gramex\python.exe: can't open file 'D:\apps\Miniconda3\envs\gramex\Scripts\gramex': [Errno 2] No such file or directory
(gramex) 
```

**Steps to reproduce.**

```bash
conda activate gramex
gramex --settings.debug=true
# and edit a py file
```

**Environment:**
 - OS: [Windows]
 - Python version: [Python 3.7.9]
 - Gramex version: [Gramex 1.67.0]

**Comment by bhatsandeep** [comment]
Noted Pratap!

@Anand S <s.anand@gramener.com> will triage the issue and update with
details as to when the fix (if required) will be available.

Regards
Sandeep

**Comment by sanand0** [comment]
[Bokeh has this problem as well](https://github.com/bokeh/bokeh/issues/8529#issuecomment-451328922). Specifically

- Tornado runs `subprocess.Popen([sys.executable] + argv)`.
- But, with Gramex, `sys.executable` is like `D:\anaconda\3.9\envs\gramex\Scripts\gramex` -- which DOES NOT EXIST. `D:\anaconda\3.9\envs\gramex\Scripts\gramex.exe` (note the `.exe` at the end) is the actual file
- So this fails.

Tornado is yet to fix this.

The workaround is to run `python -m gramex --settings.debug`. This is now documented at https://gramener.com/gramex/guide/debug/#debug-mode
