### ISSUE TITLE
MLHandler guide issues

### ISSUE THREAD

**Issue by samarthgulati** [gramener/gramex#377]
Listing issues with [MLHandler guide](https://learn.gramener.com/guide/mlhandler/) in comments, @jaidevd please have a look.

**Comment by samarthgulati** [comment]
https://learn.gramener.com/guide/mlhandler/#creating-new-models
the given yaml configuration assumes it has to be pasted under url.
might be good to add url: e.g.:

url:
  modelhandler/tutorial:
  ....

**Comment by samarthgulati** [comment]
model and api names are not consistent

creating model creates titanic.pkl
using model expects model.pkl

using model yaml says /model
given code sample says /mlhandler

**Comment by samarthgulati** [comment]
Requesting http://localhost:9988/model?Sex=male&Age=22&SibSp=1&Parch=0&Fare=7.25&Pclass=3&Embarked=S
throws 
KeyError('Sex') on local
RuntimeError('Given feature/column names do not match the ones for the data given during fit.') on guide

**Comment by samarthgulati** [comment]
Capture handler guide has deprecated documentation for v1.23
https://learn.gramener.com/guide/capturehandler/#chrome

**Comment by jaidevd** [comment]
It turns out that not only do the feature/column names have to match, they have to parsed in the _same order_ in which the model was trained. I'll fix this.
