### ISSUE TITLE
Pandas Version Conflicts

### ISSUE THREAD

**Issue by vivianshub** [gramener/gramex#387]
**Is your feature request related to a problem? Please describe.**
Gramex requires pandas version 0.25.3. This can cause a lot of conflicts in installing packages. For example, the pathing for matlibplot does not work with pandas v0.25.3. 

**Describe the solution you'd like**
Allow a range of acceptable pandas versions (particularly the new ones) that are still compatible with `filter`

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by sanand0** [comment]
@vivianshub -- a very fair point. We have an [open issue to enable Python 3.8 support](https://github.com/gramener/gramex/issues/300). Given the set of dependencies we have, we're limited to Python 3.7, and hence the need to freeze Tornado, NumPy (and hence Pandas) and other package versions to older ones.

@bhatsandeep could you suggest a timeline for the Python 3.8 release against the roadmap?

**Comment by bhatsandeep** [comment]
@Anand S ***@***.***>, it's been pending for a while. We'll
schedule it for the Gramex 1.71 release.

Regards
Sandeep

**Comment by sanand0** [comment]
This is now resolved. Since Gramex 1.75 onwards, Gramex works fine with Pandas 1 as well.
