### ISSUE TITLE
Not able to Execute code from Guide

### ISSUE THREAD

**Issue by LaxmiShivannavar** [gramener/gramex#402]
**Issue** : Unable to execute uitest code from gramex guide.

**Steps to reproduce :**

1. Open Gramex Guide.
2. Navigate to "Testing Gramex"--> "URL test"
3. Create gramextest.yaml file and paste the below code 
     
    code : 
             uitest:
                 - fetch: https://httpbin.org/get    
                   code: 200 

4. Run "pytest -s -v" command in command prompt.
5. Check whether code is executed or not.

**Expected Output** : Code should be Executed

**Actual Output**     : Code not executed

**Screenshot** : 
![image](https://user-images.githubusercontent.com/82651658/116199319-9db66580-a754-11eb-91d5-66c76cd86cc7.png)

.

**Comment by sanand0** [comment]
Actually, I think this is working as expected, @LaxmiShivannavar. If there is no `gramex.yaml` in the current directory, it is expected to do nothing. This script is:

- Warning that there is a "Missing config:" called gramex.yaml
- Saying that it "collected 0 items"
- Ending with only a warning, and no errors

So this is as expected.

**Comment by LaxmiShivannavar** [comment]
Hi Anand,

For urltest it is working fine, but unable to execute for ui test, Please
check and let me know the difference between uitest and urltest and why it
is not working for uitest.

Please find the screenshots below for both urltest and uitest

urltest :

[image: urltest.png]

uitest :

[image: uitest.png]

Regards,
Laxmi
