### ISSUE TITLE
FormHandler-Callback Usability

### ISSUE THREAD

**Issue by LaxmiShivannavar** [gramener/gramex#403]
**Issue** : Formhandler - callback is not working according to expectation.

**Steps to reproduce** :

         1. Open Gramex Guide.

         2. Navigate to "Formhandler"--> "Supported Files"

         3. Add below code in gramex.yaml file 

         code :
             
                    url: /path/to/file.txt      
                    callback: csv                

         4. Run "gramex" command in command prompt.

         5. Check whether text  file is read as CSV file or not  .
         

**Expected Output** : Text file should be read as CSV file

**Actual Output** : Error

**Screenshot**

![image](https://user-images.githubusercontent.com/82651658/116960492-276ab380-acbe-11eb-8be8-31b060410ca6.png)

**Comment by sanand0** [comment]
Thanks @LaxmiShivannavar -- good catch. Fixed via gramener/gramex-guide@0b4cbcf
