### ISSUE TITLE
Function Arguments from URL - code update

### ISSUE THREAD

**Issue by LaxmiShivannavar** [gramener/gramex#404]
**Issue** : FunctionHandler- Handler import is missing in code(.py)

**Steps to reproduce** :

     1. Open Gramex Guide.

     2. Navigate to "FunctionHandler"--> "Function Arguments from URL"

     3. Add codes in calculations.py and configuration in gramex.yaml 
     
    4. Run "gramex" command in command prompt.

    5. Check whether code is executed and able to see the output.
    
**Expected Output** : 

   Code should be executed

**Actual Output** : 
 
   Code is throwing error.

**Screenshot** : 

![image](https://user-images.githubusercontent.com/82651658/117031243-033ebf00-ad1e-11eb-90a2-fab85a1765f0.png)

**Comment by bhatsandeep** [comment]
@Laxmi Shivannavar ***@***.***> , Please close this and
open the issue against gramex-guide repo. It is a documentation issue, not
a bug.
