### ISSUE TITLE
How to schedule a task to run for every 90s using gramex schedule section

### ISSUE THREAD

**Issue by upraneelnihar** [gramener/gramex#408]
Description:
- The lowest time frequency at which we can schedule a task is at minutes, but how do schedule a task to run at every 90s.

**Comment by sanand0** [comment]
@upraneelnihar We're currently using the [python crontab](https://pypi.org/project/python-crontab/) library -- which doesn't support seconds. 

An alternative is to run a long-running async function and run the code every 90 seconds.

Why 90 seconds *EXACTLY*, though?

**Comment by upraneelnihar** [comment]
Based on the buisness requirements and optimizations we arrived at 90s as our refresh rate.

**Comment by sanand0** [comment]
Noted, @upraneelnihar. For now, I would suggest going with 60/120s if possible. If not, it's best to run this as an independent program on startup.

Deferring this feature for now.

**Comment by sanand0** [comment]
Possible spec:

```yaml
    - function: ...
    - every: 30s
```

- If `every: n` is specified, it runs every `n` seconds.
- The value can be `3 hours 30 min 10s`. Parse it using a regex or [parsedatetime](https://github.com/bear/parsedatetime)
- If hours, minutes, etc are specified along with `every`, then `every` takes priority over the Cron spec, with a warning logged on *every* run.
