### ISSUE TITLE
Excel download issue

### ISSUE THREAD

**Issue by SaurabhKhemka** [gramener/gramex#418]
I am using the below piece of code to generate an excel file.

handler.set_header('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
handler.set_header('Content-Disposition', 'attachment;filename=Table.xlsx')
return gramex.data.download(final_data, format='xlsx')

But the large values are getting converted into scientific values.
Also, how do I format the header cells in excel to display the complete header name?

**Comment by sanand0** [comment]
@SaurabhKhemka the values are getting converted into scientific values by Excel.

For example, consider this output:

![image](https://user-images.githubusercontent.com/63734/125578065-53694502-0afa-41ca-bb4a-6cc3be1ca476.png)

When I select the cells and press Ctrl-1 and format these as numbers...

![image](https://user-images.githubusercontent.com/63734/125578144-60d8d020-d919-4daa-bad0-bb2d93f1ad66.png)

... it converts them into a numeric form like this:

![image](https://user-images.githubusercontent.com/63734/125578162-38017451-75a1-4dd9-85ef-b2af2631bc5b.png)

Currently, there is no way to [apply formatting](https://xlsxwriter.readthedocs.io/example_pandas_column_formats.html) automatically.

There is an old open issue on this: #3 -- closing this issue in favor of that.
