### ISSUE TITLE
Migrate Gramex FAQ to /guide

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#42]
Migrate the Gramex FAQ's Google Doc to /guide for easier access. 

* https://docs.google.com/document/d/1ogprC1Hl7Q-fL2kxPuAWm8cYGcQ8NZvHLLgIblNzh0Q/edit

- Source: <https://code.gramener.com/cto/gramex/issues/590>
- Author: [sundeep.mallu](https://code.gramener.com/sundeep.mallu)
- Created: Wed 16 Jan 2019 04:45

**Comment by mankoven** [comment]
@sanand0 FAQ markdown file and associated images shared via email. Was not able to attach them here. 

- Need to upload the images and refer the URL in the .md file
- Add FAQ folder and make it a link in the Left Navigation bar of the /guide
