### ISSUE TITLE
GRAMEX-47 ⁃ Getting Error on connecting gramex with mongoDB database

### ISSUE THREAD

**Issue by preetika-gramener** [gramener/gramex#430]
I have tried to connect Gramex with MongoDB but when I hit the URL it is giving me this error. 
**OverflowError: Overlong 2 byte UTF-8 sequence detected when encoding string**

This is the code in the Gramex Configuration: 
`threat-insights:
    pattern: /$YAMLURL/threat-insights
    handler: FormHandler
    kwargs:
      auth: {login_url: /$YAMLURL/login/}
      threat:
        url: plugin:mongodb://localhost:27017
        database: test_db_4_06_21
        collection: threat
      `
Screen shot of the error:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/87294850/126892517-25cda4a5-a784-4273-aabf-0df3de60f799.png)

* OS: [Windows]
* Browser [Chrome]
* Python version: 2.7
* Gramex version: 1.70.0

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-47)

**Comment by sanand0** [comment]
Nice catch! Seems to be because we are [JSON-encoding a MongoDB object](https://stackoverflow.com/a/14567504/100904). Might be best to debug over a call. I'll set one up @preetika-gramener
