### ISSUE TITLE
GRAMEX-54 ⁃ gramex.data.insert fails with ArgumentError

### ISSUE THREAD

**Issue by jaidevd** [gramener/gramex#432]
**Is something not working as expected?**
`gramex.data.insert` with sqlite fails with the following error:

    ArgumentError: The argument passed to Dialect.has_table() should be a
    <class 'sqlalchemy.engine.base.Connection'>, got <class 'sqlalchemy.engine.base.Engine'>.
    Additionally, the Dialect.has_table() method is for internal dialect use only;
    please use ``inspect(some_engine).has_table(<tablename>>)`` for public API use.**Steps to reproduce.**
Try the following:

```python
gramex.data.insert('sqlite3:///somepath.sqlite3', table='foo', id="some_id", args={'x': ['x'], 'y': ['y']})
```

**Expected behavior**
Please tell us what should have happened?

**Your environment:**

* OS: Linux
* Browser: Chrome
* Python version: 3.7.11
* Gramex version: 1.71.0

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-54)

**Comment by sanand0** [comment]
Could you confirm your sqlalchemy version, please? Gramex enforces sqlalchemy<=1.3.24

SQLAlchemy 1.4+ has a [different interface](https://stackoverflow.com/q/64861610/100904) that we are aware of but don't yet support.

**Comment by jaidevd** [comment]
Oh, thanks. Something else had upgraded sqlalchemy, conforming to this fixes the issue.
