### ISSUE TITLE
Gramex 2.0

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#45]
I propose Gramex 2.0 as a:

- upgrade of Gramex 1.x
- but does not support Python 2.7 (only 3.7+)
- uses modern features like native coroutines, type annotations
- migrates to Python 3.x only libraries (e.g. Tornado 6)
- and removes deprecated features (promotes good code, reduces code size)

Pandas and Numpy have already dropped support. Tornado drops Python 2 support in [July 2019](http://www.tornadoweb.org/en/stable/releases/v5.1.0.html#deprecation-notice).

We will target March 2019 for this release.

- Source: <https://code.gramener.com/cto/gramex/issues/605>
- Author: [s.anand](https://code.gramener.com/s.anand)
- Created: Sat 26 Jan 2019 12:10

**Comment by tejesh95** [comment]
`formhandler-flags` is just a identifier and has no significance for end-user. Thinking on same lines, `pptx-table`, `cors-json`, `text` seem just a identifier. 

And `format: pptx` hints url must be `_format=pptx` but for below specific example, it is `_format=pptx-table`

![image](https://user-images.githubusercontent.com/6937958/53899040-4b3efa00-405f-11e9-9210-9a2379b4d77c.png)

**Comment by pratapvardhan** [comment]
`pptx-table, cors-json, text` are named formats. `format:` is identifier for format type. I can have multiple named formats with same `format:` type, For examples `ppt-bar:>format:pptx` and `ppt-circle:>format:pptx` and use two different format with same type `pptx`.

**Comment by sanand0** [comment]
@pratapvardhan, the problem is that sometimes, key names are unused unique identifiers (e.g. under `url:`, `alert:`, etc), but sometimes are used (e.g. under FormHandler's `kwargs.formats`, FileHandler's `kwargs.path`, etc)

@tejesh95 got confused by this. That means that others will get confused too.

In Gramex 2.0, I'd like to re-design so that keys are always used and significant.

**Comment by sanand0** [comment]
Closed as outdated. WE have dropped support from Python 2.7 in the Gramex 1.x branch, and are working towards these features incrementally.
