### ISSUE TITLE
GRAMEX-104 ⁃ CaptureHandler is not working 

### ISSUE THREAD

**Issue by LaxmiShivannavar** [gramener/gramex#463]
When I add a CaptureHandler, it should work. My kwargs are: engine: chrome, port:9900, timeout: 10.,

Actual Behavior:

Preview URL gave me an nginx 502 bad gateway even though "Gramex on" was visible. I clicked on the refresh icon next to "Gramex on". It was not clickable.

THEN I found the rocket icon (which on hover said "Launch app", thank heavens for that clarity). It showed a message box "... is taking too long to load. Check the logs." What logs? Where are the logs?

I clicked on the Preview URL again. Still a 502. No indication whether the app launched, didn't launch, nothing. The console log shows 10 HTTP 502 responses every second!!

Turns out this is due to inotify limits. But error reporting should improve.

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-104)

**Comment by sanand0** [comment]
@LaxmiShivannavar @bhatsandeep -- this is an IDE issue. Should that be reported elsewhere?

**Comment by LaxmiShivannavar** [comment]
Yes. If it is an IDE issue, needs to create it in ide repo
________________________________

**Comment by sanand0** [comment]
Closing as IDE issue.
