### ISSUE TITLE
GRAMEX-109 ⁃ ComicHandler does not have a default character

### ISSUE THREAD

**Issue by radheyakale** [gramener/gramex#468]
**Steps to reproduce.**

1. In absence of arguments in URL, "This XML file does not appear to have any style information associated with it. The document tree is shown below." message is visible.

**Expected behavior**

1. The page should have a default character

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-109)

**Comment by sanand0** [comment]
Closed via bf40fda
