### ISSUE TITLE
Expose SQL Query Editor in IDE

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#47]
### Summary

Allow for SQL query editor in IDE/ Query page

### Benefits

Allowing for SQL query will expand the no.of users who can go past Query page. Current capability only allows for Python queries. This limits the no.of users who can benefit from the flexibility that IDE allows for. 

### Usage

Include Pandas SQL for allowing for SQL querying.

- Source: <https://code.gramener.com/cto/gramex/issues/609>
- Author: [sundeep.mallu](https://code.gramener.com/sundeep.mallu)
- Created: Tue 29 Jan 2019 04:52

**Comment by pratapvardhan** [comment]
Closing, as no longer relevant.
