### ISSUE TITLE
GRAMEX-194 ⁃ Allow Gramex command line to reduce logging verbosity

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#537]
Gramex logs are too verbose. It's hard to find the relevant messages.

Allow `gramex --log.level=warning` or `--log.level=error` on the command line to control the Gramex logging level.

Raised by Aniruddha

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-194)

**Comment by jaidevd** [comment]
@sanand0 would it not be better to make the default log level `warning`?
