### ISSUE TITLE
Allow cookie settings to specify a path

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#571]
We need to set the cookie for a specific path.

This is possible by adding path params to the set_secure_cookies method within basehandler.

We need to achieve this through gramex.yaml.

Reason: This is sometimes a mandatory security requirement by InfoSec teams. Using the default path / is harmless. Even with multiple apps in the same domain using cookies, we can control that using cookie secret, subdomain, and by segregating the infra. Technically, cookies cannot be used with other apps. But this is often part of the InfoSec mandate.

Raised by Vinay Ranjan.

**Comment by vinayranjan** [comment]
@sanand0  Thanks Anand, let me verify.
