### ISSUE TITLE
Can we remove tzlocal as a dependency?

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#636]
Currently, Gramex requires tzlocal.

This is specifically to convert timestamps for influxdb. But we don't do this for any other database. (Notable, we let MongoDB manage it via the tz_aware client parameter.)

It's entirely possible for the InfluxDB and Gramex instances to be on different timezones.

Can we remove this as a dependency, allowing the database or the developer to handle this?

**Comment by jaidevd** [comment]
Agreed, sent a PR.
