### ISSUE TITLE
[Feature request] Social chart gallery with auth

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex#68]
Collaborators should be able to view charts that others created, share feedback.

**Features**
- chart access control for members to view
- ability to share feedback
- option to make chart public with randomized labels, data
- chart creators can view/edit charts they created in their profile page
- collaborators can view charts they have access to in their profile page

**Comment by sanand0** [comment]
@bkamapantula We'll plan this for Apr 2019.

**Comment by sanand0** [comment]
Closed by https://gramener.com/gramexcharts/
