### ISSUE TITLE
Test cases should not start Gramex

### ISSUE THREAD

**Issue by sanand0** [gramener/gramex#69]
Currently, running `nosetests tests` starts Gramex in the same thread. This allows us to access Gramex internals while testing, but shutdown and thread safety are problematic.

Instead, tests should not start Gramex. The CI script should start Gramex, run the tests, and shut down Gramex.

This requires reviewing all tests and refactoring some of them.

- Effort: 20-50 hours
- Benefit: CI will run reliably on Travis, local Windows systems, etc. Currently, CI (build checks) is not automated, and this is a bottleneck

**Comment by pratapvardhan** [comment]
Is this causing builds to not [terminate logically](https://travis-ci.com/gramener/gramex/builds/100352695)?

**Comment by sanand0** [comment]
Yes, exactly.

**Comment by sanand0** [comment]
Based on discussion with @mankoven this can happen after March. Priority is the Gartner event in March.

**Comment by sanand0** [comment]
I will set this up on Travis. I'll ignore the tests that are failing. We can fix these later

**Comment by jaidevd** [comment]
@sanand0 @pratapvardhan While we're at it, can we do something to quieten the build logs a bit? At more than 8k lines the logs are not readable at all.

**Comment by sanand0** [comment]
@jaidevd Good point. Let me log only warnings and above.

**Comment by sanand0** [comment]
@jaidevd I've raised the logging issue as #103 and will take it up in the next release. This issue is closed via ed450f78
