### ISSUE TITLE
https://gramex.gramener.com/ The online IDE is not opening[ required for ML course on NPTEL]

### ISSUE THREAD

**Issue by devanshukashyap** [gramener/gramex#779]
I am taking NPTEL course on Machine Learning where use of Gramex IDE is a part of course
https://elearn.nptel.ac.in/shop/partnering-courses/building-machine-learning-applications-rapidly-using-low-code-platforms/

The IDE is not opening
https://gramex.gramener.com/ 
![Capture](https://github.com/gramener/gramex/assets/10235427/6e22d7bc-26f2-4c0c-916b-32cf830a4bb8)

Please fix the issue .

**Comment by nandana-mohan-n** [comment]
I am also doing the same course and facing this issue. Was the issue solved?
