### ISSUE TITLE
Support for Firefox in gramex/apps/capture/

### ISSUE THREAD

**Issue by whimboo** [gramener/gramex#786]
**Describe the solution you'd like**
The capture package currently uses Puppeteer to automate PDF generation for web pages, but it seems that only Chrome is supported. It would be fantastic if Firefox could be added to the support matrix as well. With the release of Puppeteer 23.0.1, Firefox 129 and later is now officially supported using the WebDriver BiDi protocol. The implementation in Firefox includes all the necessary features to perform this task effectively.

For details see: https://hacks.mozilla.org/2024/08/puppeteer-support-for-firefox/

The only step that would be necessary is to update the Puppeteer package to 23.0.1 or later to get support for Firefox. No additional work should be necessary for the capture package.

Thanks!

**Comment by whimboo** [comment]
Hi @sanand0. Do you think that the above proposal would be doable for this app? Thanks.

**Comment by sanand0** [comment]
Fixed via 7fb8aa98 -- thanks @whimboo

**Comment by whimboo** [comment]
@sanand0 you are welcome. Did you as well try if it all works fine with Firefox? Or are there any issues that we have to address? I'm asking because I don't see a change in the landed code that actually sets `browser: firefox` to enable Firefox.

**Comment by whimboo** [comment]
@sanand0 could you please check my last comment? I don't think that your former patch really allows to run Firefox.
