### ISSUE TITLE
docker packaging

### ISSUE THREAD

**Issue by CalmDownKarm** [gramener/gramex#81]
Switch the docker image to use miniconda instead of anaconda - this should reduce the size of the compiled images considerably.

Also perhaps we should deploy enterprise and dev tags to dockerhub as well?

**Comment by Warlord77** [comment]
Can I pick up this issue ?

**Comment by sanand0** [comment]
Sure @Warlord77. Perhaps we could speak over a call? My number is +91 9741 552 552, and I'm reachable on mobile until tomorrow, and on WhatsApp after that.
