### ISSUE TITLE
Smart alert - Broken doc

### ISSUE THREAD

**Issue by bkamapantula** [gramener/gramex#84]
[alert-capture](https://learn.gramener.com/guide/alert/preview/?alert=alert-capture) preview example fails

![alert capture preview](https://user-images.githubusercontent.com/1143687/52893957-21b15200-31c8-11e9-90fd-8a2db87ee5b4.png)

parent link - https://learn.gramener.com/guide/alert/preview/

**Comment by sanand0** [comment]
Closed via 4051523f
